// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PredictorLibrary;

namespace PredictorLibrary.Migrations
{
    [DbContext(typeof(ResultContext))]
    partial class ResultContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("PredictorLibrary.ImageData", b =>
                {
                    b.Property<int>("ImageDataId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Data")
                        .HasColumnType("BLOB");

                    b.HasKey("ImageDataId");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("PredictorLibrary.Result", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BlobImageDataId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Class")
                        .HasColumnType("TEXT");

                    b.Property<float>("Confidence")
                        .HasColumnType("REAL");

                    b.Property<string>("Path")
                        .HasColumnType("TEXT");

                    b.HasKey("ItemId");

                    b.HasIndex("BlobImageDataId");

                    b.ToTable("SavedResults");
                });

            modelBuilder.Entity("PredictorLibrary.Result", b =>
                {
                    b.HasOne("PredictorLibrary.ImageData", "Blob")
                        .WithMany()
                        .HasForeignKey("BlobImageDataId");

                    b.Navigation("Blob");
                });
#pragma warning restore 612, 618
        }
    }
}
